### PR TITLE
BAB-273 - BAB-273-hashwrap-should-not-use-taal-m-api-for-m-api-responses

### PR DESCRIPTION
**Pull request by tonesnotes**
Lightly tested with both TAAL and GorillaPool. Pending and confirmed transactions.

### CODE REVIEW

**Comment by ty-everett** [comment]
Because this will possibly run in browsers as well as node, we may not necessarily have acces to `process.env` or environmental variables. Instead, the API key could be passed in an `options` object as a second parameter to the function. For example:

```js
const envelope = await hashwrap('txid...', { taalApiKey: '...' })
```

**Comment by ty-everett** [comment]
By convention, we have been using `const` and/or `let` over `var`, but there is no practical difference here.

**Comment by tonesnotes** [comment]
Okay…don’t see an obvious way to signal its ready for another review.

**Review by ty-everett — APPROVED** [review]

**Comment by ty-everett** [comment]
This looks good, nice work :) Merging and publishing a new package version.

**Pull request merged**
